TASK_ID_MAX_LEN = 30
TASK_ID_RE_PATT = r"^[a-z0-9]+(?:-[a-z0-9]+)*$"
TODOS_CONFIG_ENV_KEY = "TODOS_CONFIG"
TODOS_CONFIG_NAME = "./todos.toml"

# Color mapping for task states

MAX_MESSAGE_DISPLAY_LENGTH = 50
TRUNCATION_SUFFIX = "..."
MESSAGE_TRUNCATE_LENGTH = MAX_MESSAGE_DISPLAY_LENGTH - len(TRUNCATION_SUFFIX)
